# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'your_ui_file.ui' # Thay 'your_ui_file.ui' bằng tên tệp .ui thực tế của bạn
#
# Created by: PyQt5 UI code generator 5.15.x # Hoặc phiên bản tương ứng
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object): # Đổi tên class từ Ui_Form thành Ui_MainWindow để khớp với import của bạn
    def setupUi(self, MainWindow): # Đổi tên tham số từ Form thành MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow) # QMainWindow cần centralwidget
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.btn_generate_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_key.setGeometry(QtCore.QRect(670, 50, 93, 28))
        self.btn_generate_key.setObjectName("btn_generate_key")

        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget) # Đổi tên từ txt_enscrypt
        self.btn_encrypt.setGeometry(QtCore.QRect(150, 330, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")

        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget) # Đổi tên từ txt_descrypt
        self.btn_decrypt.setGeometry(QtCore.QRect(280, 330, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")

        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(110, 120, 321, 91))
        self.txt_plain_text.setObjectName("txt_plain_text")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 61, 16)) # Tăng width để vừa chữ
        self.label_2.setObjectName("label_2")

        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(110, 220, 321, 91))
        self.txt_cipher_text.setObjectName("txt_cipher_text")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 61, 16)) # Tăng width
        self.label_3.setObjectName("label_3")

        self.txt_infomation = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_infomation.setGeometry(QtCore.QRect(580, 120, 321, 91))
        self.txt_infomation.setObjectName("txt_infomation")

        self.btn_sign = QtWidgets.QPushButton(self.centralwidget) # Giữ tên txt_sign cho button
        self.btn_sign.setGeometry(QtCore.QRect(620, 330, 93, 28))
        self.btn_sign.setObjectName("btn_sign") # Đổi objectName để khớp với biến self.ui.btn_sign trong logic

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 220, 55, 16))
        self.label_4.setObjectName("label_4")

        self.btn_verify = QtWidgets.QPushButton(self.centralwidget) # Giữ tên txt_verify cho button
        self.btn_verify.setGeometry(QtCore.QRect(750, 330, 93, 28))
        self.btn_verify.setObjectName("btn_verify") # Đổi objectName để khớp với biến self.ui.btn_verify trong logic

        self.txt_signature = QtWidgets.QTextEdit(self.centralwidget) # Đây là nơi hiển thị chữ ký
        self.txt_signature.setGeometry(QtCore.QRect(580, 220, 321, 91))
        self.txt_signature.setObjectName("txt_signature")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 120, 61, 16)) # Tăng width
        self.label_5.setObjectName("label_5")

        MainWindow.setCentralWidget(self.centralwidget) # Set central widget

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Application")) # Đổi tiêu đề cửa sổ
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.btn_generate_key.setText(_translate("MainWindow", "Generate Key"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt")) # Sửa lỗi chính tả
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt")) # Sửa lỗi chính tả
        self.label_2.setText(_translate("MainWindow", "Plain text"))
        self.label_3.setText(_translate("MainWindow", "Cipher text"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.label_4.setText(_translate("MainWindow", "Signature"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "Information")) # Sửa lỗi chính tả


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())