# -*- coding: utf-8 -*-

# MainWindow implementation generated from reading ui file './lab-03/ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os 
os.environ['QT_QPA_FLATFORM_PLUGIN_PATH'] = '../platform'
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 394)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(340, 20, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_generate_key = QtWidgets.QPushButton(MainWindow)
        self.btn_generate_key.setGeometry(QtCore.QRect(670, 50, 93, 28))
        self.btn_generate_key.setObjectName("btn_generate_key")
        self.btn_encrypt = QtWidgets.QPushButton(MainWindow)
        self.btn_encrypt.setGeometry(QtCore.QRect(150, 330, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(MainWindow)
        self.btn_decrypt.setGeometry(QtCore.QRect(280, 330, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_plain_text = QtWidgets.QTextEdit(MainWindow)
        self.txt_plain_text.setGeometry(QtCore.QRect(110, 120, 321, 91))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txt_cipher_text = QtWidgets.QTextEdit(MainWindow)
        self.txt_cipher_text.setGeometry(QtCore.QRect(110, 220, 321, 91))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 55, 16))
        self.label_3.setObjectName("label_3")
        self.txt_infomation = QtWidgets.QTextEdit(MainWindow)
        self.txt_infomation.setGeometry(QtCore.QRect(580, 120, 321, 91))
        self.txt_infomation.setObjectName("txt_infomation")
        self.btn_sign = QtWidgets.QPushButton(MainWindow)
        self.btn_sign.setGeometry(QtCore.QRect(620, 330, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(510, 220, 55, 16))
        self.label_4.setObjectName("label_4")
        self.btn_verify = QtWidgets.QPushButton(MainWindow)
        self.btn_verify.setGeometry(QtCore.QRect(750, 330, 93, 28))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_signature = QtWidgets.QTextEdit(MainWindow)
        self.btn_signature.setGeometry(QtCore.QRect(580, 220, 321, 91))
        self.btn_signature.setObjectName("btn_signature")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(510, 120, 55, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.btn_generate_key.setText(_translate("MainWindow", "Generate Key"))
        self.btn_encrypt.setText(_translate("MainWindow", "Enscrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Descrypt"))
        self.label_2.setText(_translate("MainWindow", "Plain text"))
        self.label_3.setText(_translate("MainWindow", "Cipher text"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.label_4.setText(_translate("MainWindow", "Signature"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "Infomation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
